language: android
android:
  components:
  - build-tools-25.0.3
  - android-25
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - extra-android-.+
before_install:
- openssl aes-256-cbc -K $encrypted_d80c35a8c544_key -iv $encrypted_d80c35a8c544_iv
  -in travis-release-key.jks.enc -out travis-release-key.jks -d
- mkdir "$ANDROID_HOME/licenses" | echo "ok"
- echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
script:
- "./gradlew build"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
env:
  global:
  - secure: WtkpCZEBbm6WJ/h6TBoZEebsvcDgX5cW1hpPxZb2JCf00soDUvehhGOUgoMMcwlwqNzhb5D14sbvg9E3Xk9aYm0MODWnlz5NewG7ZWnjCo/RNi6w43WLb8ZwS43pXOIfoXxipKtccuIQKYlRFPvIx7uRDBsRJpJPg3ZDWRmu+j78qGBEIyUEJNb4Lng+Er1hfn+rH/CB5+XmAOIm55vlkoXxZdLYYIr7yeNMtnBmUYsUc9j8k6PN3imSuTPvCT/hrKsg5wN+RzzwVm0MhStf1tM6m11nFhvAMOeE+Wx6jTfleOQkC7K/nVYBs2vcQpaNg/c7DxHudk1t7zDvk+x8ifuc7UK6pce8SgYFMvlivDspsQR0C9Lsf93H7XkV2fva3ZuATyIxsS94fnwWzTFCGqvaeDQpGQmb9qojjd6Njjw5+gopepkWAUX1VsxgecjvlHo2MMpzMa7cnKCciOVhkjn02VVm5OG7Suleu8BzjyF0UaaN/NNEWn/KssYoxuEGcnxFmHHPVogkymN8LLeLvZViDBocAbMn5TZMOESfWLflrW2Ka0vlbNZJl5vDke2gv1pBU4YUi/La2ImQ3bnuLY3crbUK8Q0uXDP2FhJvujSh11sbjQHaZg3WXa0jgUO2JlEOv9aBFJskQbkrMHILUX/ot7HR35OgzV9EaarPLgM=
  - secure: z00nWRuMqDvh/Ajet9EhPvyw2nVz2mNu+4LikfarPh2EJIq0843ioLscdA8+O5Y07ilZzTl5EpzjphR1Bhv0dRvVnb6kPzjSJ4uR51D9oI+385BjyP5z+3RtxzsPMpsVHpTMocwarNZCM7+VRky/H0NUBDzuNctD5NH9hCO6XnwGGFcFiIoKSYjiueqKz4DiUv5HwLO2T0t9b0zkkvHPkIzIkJLvZ8Rj86s41IMVtH34hZXGB/618J6UK82kYs6x8ICrBFq+oxSv0hDwMsOsvCKpbXOIkF6ueXs6U3KQQebn4WbvPWYOPG5+EMXlDRLUDZJF1aRnZVffArd4x6hQ50xVJ/xD20TgE/3LUrbTn89wlu8v+3jOLioMA3TJinr0iZJk/oEBzsbpj1cj0cYmeWeGRGF4/B6E1XjhdC1Xc+G/Ch7Vm7+nf69jaB799/vkwDkncNoH0kbXyaQSKLnnVZ6aiHv6qaC7RLjaQESy12K4RzLInKEgaKm0DI3U+aAcdaU/6GXIdCL0P0IdhbeimKTWUr7d8436xzlGtAtwtxeKEIY/SKk64DPURfp22E3wLBMlTkKWlKQwgjrKk+U0Sl/Op79D70oD3wQdBwP33bTNRXar8+JWjRH9CpLvIGga7NEQLIl7ifII/F9EgNvQo9AVKxaQSlxt9OckViy4Ds8=
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: D5dviU7f2k5HC1WSNNlm8KRfachZhLry5SvHdf0eZ3ynCB4eBPsax/tjwIry6GZMtYkBLiCS+C2hdiZmzeemywPgV0i/dkjpX1/iPJC1XOyM3nz69ybgHrkYpOMm4Gn05gu9WDvARonM9EWtjwRNtKxDEC7JPTV3+f3Yd0hm5s9LUXD4NjBlwVocXw/vwNztjFjuKtgNg6nCk6F/BQfxQXrtHRBWkXm5Tc/KtCjJk4blDOyub1Hix8ymTkh8CZ2dStXn6Ckv215KWdSqubonzYeL7z5fudcFwgEDLQB7YJpAdQzepwZL6GkC6c6cr0zYTcWR1gUGEgo31tCkMq+cGZZPtv4omcuuWxy0U7u0Ckuk4HLleAP4muibhNAs1yU+4dE5n/0sxjmCgHKMvzpVShWWvGAqHdfnQbsOs1TNN2QPfYvIPGrSC7nzxCtGVmspYsoop0OC7Hw0CuNwDAt1jkc8jTWgkc41p+6jkxAevUCmsNi09oL9luYWm3OobtYUpZVptxA8GehLl1ATCImPHRgDfhwaaLCJLseXTJcq8VyT553y4eX254mA8/E2TkNf8FtzABtk53asjAEC+cz1u9YNaZ7JhU3klMuoaFCM9G/mZyuhUxpfFhzbtF7B2Hgm62HQW872IbuVqUAcQgFFLSXFSGBN9RhnL9FBh4y/aBk=
  file:
    - app/build/outputs/apk/app-debug.apk
    - app/build/outputs/apk/app-release.apk 
  on:
    repo: coffeemakr/OST
    tags: true
