/**
 * Trasport API
 * The Transport API allows interested developers to build their own applications using public timetable data, whether they're on the web, the desktop or mobile devices. The aim of this inofficial API is to cover public transport within Switzerland. If you are looking for an officially supported source or need to download all data e.g in GTFS format, please check opendata.swiss. The source code of the Transport API can be found on GitHub, please ask any technical questions there. If you need a direct contact write an email to transport@opendata.ch. In order to be kept update on the future development of this API, please subscribe to our low-traffic Google Group.
 *
 * OpenAPI spec version: 1
 * Contact: transport@opendata.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.unstable.transport.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Operation information for a connection.
 **/
@ApiModel(description = "Operation information for a connection.")
public class Service {
  
  @SerializedName("regular")
  private String regular = null;

  /**
   * Information about how regular a connection operates.
   **/
  @ApiModelProperty(value = "Information about how regular a connection operates.")
  public String getRegular() {
    return regular;
  }
  public void setRegular(String regular) {
    this.regular = regular;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Service service = (Service) o;
    return (this.regular == null ? service.regular == null : this.regular.equals(service.regular));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.regular == null ? 0: this.regular.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    
    sb.append("  regular: ").append(regular).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
